Models/Inventory.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Personal_Inventory.Models
{
    public class Inventory
    {
        public int ID { get; set; }
        public string ItemDesc { get; set; }
        [Display(Name = "Brand")]
        public int BrandID { get; set; }
        [Display(Name = "Category")]
        public int CategoryID { get; set; }
        [Display(Name = "Sub-Category")]
        public int SubCategoryID { get; set; }
        public int LocationID { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateEntered { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateChanged { get; set; }
        [DataType(DataType.Date)]
        public DateTime DatePurchased { get; set; }
        public float Quantity { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem>? ListofCategories { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem>? ListofBrands { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem>? ListofSubCategories { get; set; }
    }
}

Models/InventoryView.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Personal_Inventory.Models
{
    public class InventoryView
    {
        public int ID { get; set; }
        public string? ItemDesc { get; set; }
        [Display(Name = "Brand")]
        public string? BrandName { get; set; }
        [Display(Name = "Category")]
        public string? CategoryName { get; set; }
        [Display(Name = "Sub-Category")]
        public string? SubCategoryName { get; set; }
        public int LocationID { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateEntered { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateChanged { get; set; }
        [DataType(DataType.Date)]
        public DateTime DatePurchased { get; set; }
        public float Quantity { get; set; }
    }
}

Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Personal_Inventory.Data;
using Personal_Inventory.Models;

namespace Personal_Inventory.Controllers
{
    public class InventoriesController : Controller
    {
        private readonly Personal_InventoryContext _context;

        public InventoriesController(Personal_InventoryContext context)
        {
            _context = context;
        }

        // GET: Inventories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Inventory.ToListAsync());
        }

        // GET: Inventories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .FirstOrDefaultAsync(m => m.ID == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        //public IActionResult Create()
        //{
        //    //Populate DropDownList binding values
        //    var model = new Inventory
        //    {
        //        ItemDesc = null,
        //        ListofBrands = _context.Brand.Select(c => new SelectListItem
        //        {
        //            Value = c.ID.ToString(),
        //            Text = c.BrandName
        //        }),
        //        ListofCategories = _context.Category.Select(c => new SelectListItem
        //        {
        //            Value = c.ID.ToString(),
        //            Text = c.CategoryName
        //        }),
        //        //Needs to connect to selected Category by user: 1 is just a test. .Where(x => x.CategoryId == 1)
        //        ListofSubCategories = _context.SubCategory.Select(c => new SelectListItem
        //        {
        //            Value = c.Id.ToString(),
        //            Text = c.SubCategoryName
        //        }),
        //        LocationID = 0,
        //        DateEntered = DateTime.Now,
        //        DateChanged = DateTime.Now,
        //        DatePurchased = DateTime.Now,
        //        Quantity = 0
        //    };
        //    return View(model);
        //}

        public IActionResult Create()
        {
            var brands = new SelectList(_context.Brand.ToList(), "ID", "BrandName");
            var categories = new SelectList(_context.Category.ToList(), "ID", "CategoryName");
            var subCategories = new SelectList(_context.SubCategory.ToList(), "Id", "SubCategoryName");

            var viewModel = new Inventory
            {
                ItemDesc = null,
                ListofBrands = brands,
                ListofCategories = categories,
                ListofSubCategories = subCategories,
                LocationID = 0,
                DateEntered = DateTime.Now,
                DateChanged = DateTime.Now,
                DatePurchased = DateTime.Now,
                Quantity = 0
            };

            return View(viewModel);
        }

        public IActionResult getSubCategories(int id)
        {
            var subCategories = new List<SubCategory>();
            subCategories = getSubCategoriesFromDatabaseByCategoryID(id); //call repository
            return Json(subCategories);
        }

        public List<SubCategory> getSubCategoriesFromDatabaseByCategoryID(int id)
        {
            return _context.SubCategory.Where(c => c.CategoryId == id).ToList();
        }

        // POST: Inventories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ItemDesc,BrandID,CategoryID,SubCategoryID,LocationID,DateEntered,DateChanged,DatePurchased,Quantity")] Inventory newInventory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(newInventory);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Inventories");
            }
            return View(newInventory);
        }

    // GET: Inventories/Edit/5
    public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory.FindAsync(id);
            if (inventory == null)
            {
                return NotFound();
            }
            return View(inventory);
        }

        // POST: Inventories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ItemDesc,BrandID,CategoryID,SubCategoryID,LocationID,DateEntered,DateChanged,DatePurchased,Quantity")] Inventory inventory)
        {
            if (id != inventory.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inventory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventoryExists(inventory.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(inventory);
        }

        // GET: Inventories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .FirstOrDefaultAsync(m => m.ID == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // POST: Inventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inventory = await _context.Inventory.FindAsync(id);
            _context.Inventory.Remove(inventory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InventoryExists(int id)
        {
            return _context.Inventory.Any(e => e.ID == id);
        }
    }
}

Controllers/InventoriesViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Personal_Inventory.Data;
using Personal_Inventory.Models;

namespace Personal_Inventory.Controllers
{
    public class InventoriesViewController : Controller
    {
        private readonly Personal_InventoryContext _context;

        public InventoriesViewController(Personal_InventoryContext context)
        {
            _context = context;
        }

        // GET: Inventories
        public async Task<IActionResult> Index()
        {
            return View(await _context.InventoryView.ToListAsync());
        }

        // GET: Inventories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.InventoryView
                .FirstOrDefaultAsync(m => m.ID == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // GET: Inventories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Inventories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ItemDesc,BrandID,CategoryID,SubCategoryID,LocationID,DateEntered,DateChanged,DatePurchased,Quantity")] Inventory newInventory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(newInventory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(newInventory);
        }

        // GET: Inventories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory.FindAsync(id);
            if (inventory == null)
            {
                return NotFound();
            }
            return View(inventory);
        }

        // POST: Inventories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ItemDesc,BrandID,CategoryID,SubCategoryID,LocationID,DateEntered,DateChanged,DatePurchased,Quantity")] Inventory inventory)
        {
            if (id != inventory.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inventory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventoryExists(inventory.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(inventory);
        }

        // GET: Inventories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventory
                .FirstOrDefaultAsync(m => m.ID == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // POST: Inventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inventory = await _context.Inventory.FindAsync(id);
            _context.Inventory.Remove(inventory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InventoryExists(int id)
        {
            return _context.Inventory.Any(e => e.ID == id);
        }
    }
}

Views/Inventories/Create.cshtml
@model Personal_Inventory.Models.Inventory

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Inventory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemDesc" class="control-label"></label>
                <input asp-for="ItemDesc" class="form-control" />
                <span asp-validation-for="ItemDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandID" class="control-label"></label>
                <br />
                <select asp-for="BrandID" asp-items="Model.ListofBrands"><option disabled selected>--- SELECT ---</option></select>
                <span asp-validation-for="BrandID" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="CategoryID"></label>
                <select asp-for="CategoryID" asp-items="Model.ListofCategories" class="form-control" id="category-target"><option disabled selected>--- SELECT ---</option></select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="SubCategoryID"></label>
                <select asp-for="SubCategoryID" asp-items="Model.ListofSubCategories" class="form-control" id="subCategory-target"><option disabled selected>--- SELECT ---</option></select>
                <span asp-validation-for="SubCategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationID" class="control-label"></label>
                <input asp-for="LocationID" class="form-control" />
                <span asp-validation-for="LocationID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEntered" class="control-label"></label>
                <input asp-for="DateEntered" class="form-control" />
                <span asp-validation-for="DateEntered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateChanged" class="control-label"></label>
                <input asp-for="DateChanged" class="form-control" />
                <span asp-validation-for="DateChanged" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePurchased" class="control-label"></label>
                <input asp-for="DatePurchased" class="form-control" />
                <span asp-validation-for="DatePurchased" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Inventories" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

    <script>
        $(document).ready(function () {
          $("#category-target").on("change", function () {
            $list = $("#subCategory-target");
            $.ajax({
                url: "/Inventories/getSubCategories",
                type: "GET",
                data: { id: $("#category-target").val() }, //id of the category which is used to extract subcategory
                traditional: true,
                success: function (result) {
                    $list.empty();
                    $.each(result, function (i, item) {
                        $list.append('<option value="' + item["id"] + '"> ' + item["subCategoryName"] + ' </option>');
                        //console.log(item)
                    });
                },
                error: function () {
                    alert("Something went wrong");
                }
            });
          });
        });
    </script>
}

Views/Inventories/Delete.cshtml
@model Personal_Inventory.Models.Inventory

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubCategoryID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubCategoryID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEntered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEntered)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateChanged)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateChanged)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePurchased)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePurchased)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="InventoriesView" asp-action="Index">Back to List</a>
    </form>
</div>

Views/Inventories/Details.cshtml
@model Personal_Inventory.Models.Inventory

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubCategoryID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubCategoryID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEntered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEntered)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateChanged)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateChanged)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePurchased)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePurchased)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-controller="InventoriesView" asp-action="Index">Back to List</a>
</div>

Views/Inventories/Edit.cshtml
@model Personal_Inventory.Models.Inventory

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Inventory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ItemDesc" class="control-label"></label>
                <input asp-for="ItemDesc" class="form-control" />
                <span asp-validation-for="ItemDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandID" class="control-label"></label>
                <input asp-for="BrandID" class="form-control" />
                <span asp-validation-for="BrandID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <input asp-for="CategoryID" class="form-control" />
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubCategoryID" class="control-label"></label>
                <input asp-for="SubCategoryID" class="form-control" />
                <span asp-validation-for="SubCategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationID" class="control-label"></label>
                <input asp-for="LocationID" class="form-control" />
                <span asp-validation-for="LocationID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEntered" class="control-label"></label>
                <input asp-for="DateEntered" class="form-control" />
                <span asp-validation-for="DateEntered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateChanged" class="control-label"></label>
                <input asp-for="DateChanged" class="form-control" />
                <span asp-validation-for="DateChanged" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePurchased" class="control-label"></label>
                <input asp-for="DatePurchased" class="form-control" />
                <span asp-validation-for="DatePurchased" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="InventoriesView" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Inventories/Index.cshtml
@model IEnumerable<Personal_Inventory.Models.Inventory>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrandID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubCategoryID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEntered)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateChanged)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePurchased)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrandID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubCategoryID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEntered)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateChanged)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePurchased)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>